# application
debug: true
loggerConfig: 'logging_utils/simple_logger_config.yaml'
pathToCrt: 'certificates/server.crt'
pathToKey: 'certificates/server.key'

# Mongo
mongo:
  prefix: 'mongodb://'
  urlPattern: 'mongodb://{}:{}@{}'
  host: 'admsg.ru'
  user: 'admsg'
  password: 'gfhjkm1lkz2flv0pu'
  admsgConfigDB: 'admsg_config'
  bot:
    db: 'bot'
    collection:
      viber: 'viber'
      telegram: 'telegram'
  userTracker:
    db: 'userTracker'
    collection:
      map: 'map'

# bots
bot:
  webhookUrl: 'https://admsg.ru:{}/'
  deeplink:
    telegram: 'https://telegram.me/{}?start={}'
    viber: 'https://telegram.me/{}?start={}'
  telegram:
    deeplink: 'https://telegram.me/{}?start={}'
    acceptablePorts: [443, 80, 88, 8443]
  trackerUrlPattern: 'http://admsg.ru/rd?{}'
